# Generated by Django 4.2 on 2026-04-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_employeeprofile_id_alter_leaveapplication_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='jumlah_hari',
            field=models.IntegerField(default=0),
        ),
    ]
