# Generated by Django 4.2 on 2026-04-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_leaveapplication_jumlah_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='hr_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='mc_files/'),
        ),
    ]
