# Generated by Django 4.2 on 2026-04-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_leaveapplication_hr_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='total_leave_quota',
            field=models.IntegerField(default=24),
        ),
    ]
