# Generated by Django 4.2 on 2026-04-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_employeeprofile_total_leave_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='total_leave_quota',
            field=models.IntegerField(default=48),
        ),
    ]
