# Generated by Django 4.2 on 2026-04-26 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0008_employeeprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='supervisor_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Setuju', 'Setuju'), ('Tidak Setuju', 'Tidak Setuju')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
